### ISSUE TITLE
sed error on osx

### ISSUE THREAD

**Issue by md-seb** [cris691/servedata#39]
Hi, I'm trying to run this on osx. dev_views.sh fails

> ./dev_views.sh && npm run pack && npm run dev-db
sed: 1: "public/dev-console.html": extra characters at the end of p command
npm ERR! code ELIFECYCLE

This is the line causing error
find public/*.html -type f -exec sed -i "s/from '\/\w\+\//from '\/src\//g" {} +

https://stackoverflow.com/questions/39325759/sed-on-mac-extra-characters-after-p-command
has potential solution, but I don't know where to put that semicolon.

Any help would be appreciated.
Thanks

**Comment by cris691** [comment]
Hey! Sorry about the late reply, I only just now saw your issue. I'll take a look

**Comment by cris691** [comment]
SHould be fixed now :p :) x
